# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.22

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /mnt/c/Users/borsh/Desktop/MACHIN_TURPING

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /mnt/c/Users/borsh/Desktop/MACHIN_TURPING

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /mnt/c/Users/borsh/Desktop/MACHIN_TURPING/CMakeFiles /mnt/c/Users/borsh/Desktop/MACHIN_TURPING//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /mnt/c/Users/borsh/Desktop/MACHIN_TURPING/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named MACHIN_TURPING

# Build rule for target.
MACHIN_TURPING: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 MACHIN_TURPING
.PHONY : MACHIN_TURPING

# fast build rule for target.
MACHIN_TURPING/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/MACHIN_TURPING.dir/build.make CMakeFiles/MACHIN_TURPING.dir/build
.PHONY : MACHIN_TURPING/fast

src/Checker.o: src/Checker.c.o
.PHONY : src/Checker.o

# target to build an object file
src/Checker.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/MACHIN_TURPING.dir/build.make CMakeFiles/MACHIN_TURPING.dir/src/Checker.c.o
.PHONY : src/Checker.c.o

src/Checker.i: src/Checker.c.i
.PHONY : src/Checker.i

# target to preprocess a source file
src/Checker.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/MACHIN_TURPING.dir/build.make CMakeFiles/MACHIN_TURPING.dir/src/Checker.c.i
.PHONY : src/Checker.c.i

src/Checker.s: src/Checker.c.s
.PHONY : src/Checker.s

# target to generate assembly for a file
src/Checker.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/MACHIN_TURPING.dir/build.make CMakeFiles/MACHIN_TURPING.dir/src/Checker.c.s
.PHONY : src/Checker.c.s

src/I_O_File.o: src/I_O_File.c.o
.PHONY : src/I_O_File.o

# target to build an object file
src/I_O_File.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/MACHIN_TURPING.dir/build.make CMakeFiles/MACHIN_TURPING.dir/src/I_O_File.c.o
.PHONY : src/I_O_File.c.o

src/I_O_File.i: src/I_O_File.c.i
.PHONY : src/I_O_File.i

# target to preprocess a source file
src/I_O_File.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/MACHIN_TURPING.dir/build.make CMakeFiles/MACHIN_TURPING.dir/src/I_O_File.c.i
.PHONY : src/I_O_File.c.i

src/I_O_File.s: src/I_O_File.c.s
.PHONY : src/I_O_File.s

# target to generate assembly for a file
src/I_O_File.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/MACHIN_TURPING.dir/build.make CMakeFiles/MACHIN_TURPING.dir/src/I_O_File.c.s
.PHONY : src/I_O_File.c.s

src/algorithm.o: src/algorithm.c.o
.PHONY : src/algorithm.o

# target to build an object file
src/algorithm.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/MACHIN_TURPING.dir/build.make CMakeFiles/MACHIN_TURPING.dir/src/algorithm.c.o
.PHONY : src/algorithm.c.o

src/algorithm.i: src/algorithm.c.i
.PHONY : src/algorithm.i

# target to preprocess a source file
src/algorithm.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/MACHIN_TURPING.dir/build.make CMakeFiles/MACHIN_TURPING.dir/src/algorithm.c.i
.PHONY : src/algorithm.c.i

src/algorithm.s: src/algorithm.c.s
.PHONY : src/algorithm.s

# target to generate assembly for a file
src/algorithm.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/MACHIN_TURPING.dir/build.make CMakeFiles/MACHIN_TURPING.dir/src/algorithm.c.s
.PHONY : src/algorithm.c.s

src/main.o: src/main.c.o
.PHONY : src/main.o

# target to build an object file
src/main.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/MACHIN_TURPING.dir/build.make CMakeFiles/MACHIN_TURPING.dir/src/main.c.o
.PHONY : src/main.c.o

src/main.i: src/main.c.i
.PHONY : src/main.i

# target to preprocess a source file
src/main.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/MACHIN_TURPING.dir/build.make CMakeFiles/MACHIN_TURPING.dir/src/main.c.i
.PHONY : src/main.c.i

src/main.s: src/main.c.s
.PHONY : src/main.s

# target to generate assembly for a file
src/main.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/MACHIN_TURPING.dir/build.make CMakeFiles/MACHIN_TURPING.dir/src/main.c.s
.PHONY : src/main.c.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... MACHIN_TURPING"
	@echo "... src/Checker.o"
	@echo "... src/Checker.i"
	@echo "... src/Checker.s"
	@echo "... src/I_O_File.o"
	@echo "... src/I_O_File.i"
	@echo "... src/I_O_File.s"
	@echo "... src/algorithm.o"
	@echo "... src/algorithm.i"
	@echo "... src/algorithm.s"
	@echo "... src/main.o"
	@echo "... src/main.i"
	@echo "... src/main.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

